import{s as p,i as a}from"./assets/vendor-1d1bb5a2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const d=document.querySelector(".object-list"),m=new p(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250,showCounter:!1}),f=function(s){return s.map(({views:o,comments:t,downloads:n,likes:e,webformatURL:r,tags:i,largeImageURL:u})=>`<li>
        <div class="img-box">
        <a href="${u}">
        <img class="img" src="${r}" alt="${i}" width="360" height="200">
        </a>
        <ul class="value-list">
        <li class="likes value-item"><p class="article">Likes</p><p class="value">${e}</p></li>
        <li class="views value-item" ><p class="article">Views</p><p class="value">${o}</p></li>
        <li class="comments value-item"><p class="article">Comments</p><p class="value">${t}</p></li>
        <li class="downloads value-item"><p class="article">Downloads</p><p class="value">${n}</p></li>
        </ul></div>
        </li>`).join("")},h=function(s){d.insertAdjacentHTML("beforeend",s),m.refresh()},y="https://pixabay.com/api/",g="43211197-e02e136a3ee46bcda7d5bf66f";function b(s=""){const o=new URLSearchParams({key:g,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${y}/?${o}`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const c=document.querySelector(".search-form"),v=document.querySelector("input"),L=document.querySelector(".object-list"),l=document.querySelector(".loader-box");c.addEventListener("submit",w);function w(s){if(s.preventDefault(),!v.value)return a.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",closeOnClick:!0,position:"topCenter"});const o=s.currentTarget.elements.search.value.trim();l.style.display="flex",b(o).then(t=>{if(!t.total)return l.style.display="none",a.info({message:"Don't found",closeOnClick:!0,position:"topCenter"});console.log(t),L.innerHTML=f(t.hits),h(),c.reset(),l.style.display="none"}).catch(t=>(l.style.display="none",a.error({message:`${t.message}`,backgroundColor:"red",position:"topCenter"})))}
//# sourceMappingURL=commonHelpers.js.map
