import{s as u,i as p}from"./assets/vendor-1d1bb5a2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const d=document.querySelector(".object-list"),m=new u(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250,showCounter:!1}),f=function(s){return s.map(({views:o,comments:r,downloads:i,likes:e,webformatURL:t,tags:a,largeImageURL:n})=>`<li>
        <div class="img-box">
        <a href="${n}">
        <img class="img" src="${t}" alt="${a}" width="360" height="200">
        </a>
        <ul class="value-list">
        <li class="likes value-item"><p class="article">Likes</p><p class="value">${e}</p></li>
        <li class="views value-item" ><p class="article">Views</p><p class="value">${o}</p></li>
        <li class="comments value-item"><p class="article">Comments</p><p class="value">${r}</p></li>
        <li class="downloads value-item"><p class="article">Downloads</p><p class="value">${i}</p></li>
        </ul></div>
        </li>`).join("")},h=function(s){d.insertAdjacentHTML("beforeend",s),m.refresh()},y="https://pixabay.com/api/",g="43211197-e02e136a3ee46bcda7d5bf66f";function b(s=""){const o=new URLSearchParams({key:g,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${y}/?${o}`).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()})}const l=document.querySelector(".search-form"),v=document.querySelector("input"),L=document.querySelector(".object-list"),c=document.querySelector(".loader-box");l.addEventListener("submit",w);function w(s){if(s.preventDefault(),!v.value)return p.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",closeOnClick:!0,position:"topCenter"});const o=s.currentTarget.elements.search.value.trim();c.style.display="flex",b(o).then(r=>{L.innerHTML=f(r.hits),h(),l.reset(),c.style.display="none"}).catch(r=>{console.log(r),c.style.display="none"})}
//# sourceMappingURL=commonHelpers.js.map
