import{s as d,i as n}from"./assets/vendor-5c957d73.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const m=function(s){return s.map(({views:o,comments:t,downloads:a,likes:e,webformatURL:r,tags:i,largeImageURL:p})=>`<li>
        <div class="img-box">
        <a href="${p}">
        <img class="img" src="${r}" alt="${i}" width="360" height="200">
        </a>
        <ul class="value-list">
        <li class="likes value-item"><p class="article">Likes</p><p class="value">${e}</p></li>
        <li class="views value-item" ><p class="article">Views</p><p class="value">${o}</p></li>
        <li class="comments value-item"><p class="article">Comments</p><p class="value">${t}</p></li>
        <li class="downloads value-item"><p class="article">Downloads</p><p class="value">${a}</p></li>
        </ul></div>
        </li>`).join("")},f="https://pixabay.com/api/",h="43211197-e02e136a3ee46bcda7d5bf66f";function y(s=""){const o=new URLSearchParams({key:h,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${f}/?${o}`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const c=document.querySelector(".search-form"),g=document.querySelector("input"),u=document.querySelector(".object-list"),l=document.querySelector(".loader-box"),b=new d(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250,showCounter:!1});c.addEventListener("submit",v);function v(s){if(s.preventDefault(),!g.value)return n.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",closeOnClick:!0,position:"topCenter"});u.textContent="";const o=s.currentTarget.elements.search.value.trim();l.style.display="flex",y(o).then(t=>{if(!t.total)return l.style.display="none",n.info({message:"Don't found",closeOnClick:!0,position:"topCenter"});console.log(t),L(t.hits),c.reset(),l.style.display="none"}).catch(t=>(l.style.display="none",n.error({message:`${t.message}`,backgroundColor:"red",position:"topCenter"})))}function L(s){u.insertAdjacentHTML("beforeend",m(s)),b.refresh()}
//# sourceMappingURL=commonHelpers.js.map
